name: GitHub Pages
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: actions/checkout
        uses: actions/checkout@v3

      - name: Build Project
        uses: actions/setup-node@master
        with:
          node-version: '16.x'
      - run: npm install  --legacy-peer-deps

      - name: Build
        run: npm run generate

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.DEPLOY_TOKEN  }}
          publish_dir: ".output/public"
          force_orphan: true
